### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by chris-huxtable** [crystal-lang-tools/Crystal.tmbundle#13]
There is no licence on this project. To avoid ambiguity I think it should have one. I would like to propose the ISC Licence. 

I would like approval to add it from the other two contributors? @huacnlee? @reitermarkus?

ISC Licence:

Copyright 2017 Jason Lee

Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

**Comment by huacnlee** [comment]
MIT

**Comment by chris-huxtable** [comment]
I am ok with MIT. Though its, for all intents and purposes, identical to ISC. The main advantage of ISC is simplicity.

https://choosealicense.com/licenses/isc/
https://choosealicense.com/licenses/mit/

**Comment by faustinoaq** [comment]
Oh I din't know about ISC License, although I think we're ok with MIT, Feel free to publish a PR :+1:

**Comment by chris-huxtable** [comment]
Merged PR. Closing
