### ISSUE TITLE
Fails to install on TextMate version 2.0-rc.22

### ISSUE THREAD

**Issue by belgoros** [crystal-lang-tools/Crystal.tmbundle#17]
I followed the instructions to install the bundle, everything was OK but Crystal is not yet available in bundles list in Textmate:
<img width="264" alt="screenshot 2019-02-06 at 10 45 50" src="https://user-images.githubusercontent.com/83579/52332998-684ec180-29fc-11e9-810a-0e31b286ad59.png">

Here is the list of bundles available in `~/Library/Application\ Support/TextMate/Bundles` directory:
```
cd ~/Library/Application\ Support/TextMate/Bundles
ll
total 0
drwxr-xr-x 11 Serguei 1000 352 Feb  6 10:34 Crystal.tmbundle
drwxr-xr-x 18 Serguei 1000 576 Aug  2  2018 Elixir.tmbundle
drwxr-xr-x 10 Serguei 1000 320 Nov  8  2017 avian-missing.tmbundle
drwxr-xr-x 10 Serguei 1000 320 Mar 17  2017 old_avian-missing.tmbundle
```
I'm on `macOS 10.14.3`. What a I missing ? Thank you.

**Comment by vanhecke** [comment]
TextMate2 will install the bundle when you just "File > Open" it.

**Comment by belgoros** [comment]
@vanhecke Yeah, thank you. In this case, it would be worth to precise this _old and classic way_ to install a TM bundle in the README.
