### ISSUE TITLE
Installing this bundle causes problems with Ruby line commenting

### ISSUE THREAD

**Issue by eliduke** [crystal-lang-tools/Crystal.tmbundle#3]
I installed this bundle, and then whenever I tried to comment out some lines in a Ruby file, it would use CSS commenting syntax `/* */` instead of Ruby syntax `#`. I deleted the bundle and that fixed the problem. Not sure what the deal is exactly, but thought I should let you know.

Thanks!

**Comment by brandonzylstra** [comment]
This is a big problem.

**Comment by chris-huxtable** [comment]
Is this not already fixed by the patches introduced by @reitermarkus?

**Comment by eliduke** [comment]
I just installed the bundle again, and it seems to be working just fine!

@brandondrew Wanna try installing the bundle again and see if it's fixed for you?

**Comment by hovsater** [comment]
@eliduke sorry for bothering you so many years later. But may I close this issue?
