### ISSUE TITLE
Join to Crystal Tools organization

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang-tools/Crystal.tmbundle#4]
Hi @huacnlee , some Crystal community members have the idea of a [Crystal Tools organization](https://github.com/crystal-lang-tools) inspired by [Julia Editor Support organization](https://github.com/JuliaEditorSupport).

We are adding repositories for sublime, emacs, vim, vscode, atom, etc. All in one place well documented easier to follow, collaborate and maintain. :-)

If you accept the proposal of move your repo to Crystal Tool organization, leave a message in [Gitter room](https://gitter.im/crystal-scry/Lobby?source=orgpage) first.

Thanks you for your Crystal support. 💓

**Comment by huacnlee** [comment]
Yes, it is my honored to move this repo into the official organization.

**Comment by keplersj** [comment]
Your invitation to join the `textmate` team in the crystal-lang-tool organization has been sent. Welcome! Please reach out to either myself or @faustinoaq if you have any questions.

**Comment by huacnlee** [comment]
Done
